on: [push, pull_request]
name: Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.0'
    - name: Run build
      run: make
    - name: Run tests
      run: make test
